/** Bundled classic drill rows (spec 0012 AC-4). L1 allows repeats, L2/L3 never repeat back to back. */
import { splitUnits } from "./preeti";
import { drillPassesDifficulty } from "./classicLayout";
import type { Lesson } from "./datastore";

export const CLASSIC_DRILLS: Lesson[] = [
  {
    id: "cl-home-1",
    layout: "traditional",
    title: "Home L1",
    prompt: "ममम पपप ममम पपप ममम पपप ममम",
    order: 101,
    category: "home",
    difficulty: 1,
  },
  {
    id: "cl-home-2",
    layout: "traditional",
    title: "Home L2",
    prompt: "म प न त म प न त प म त न",
    order: 102,
    category: "home",
    difficulty: 2,
  },
  {
    id: "cl-home-3",
    layout: "traditional",
    title: "Home L3",
    prompt: "म प न त क स म न प त क स प म त न क प स म",
    order: 103,
    category: "home",
    difficulty: 3,
  },
  {
    id: "cl-top-1",
    layout: "traditional",
    title: "Top L1",
    prompt: "गगग चचच गगग चचच गगग चचच गगग",
    order: 104,
    category: "top",
    difficulty: 1,
  },
  {
    id: "cl-top-2",
    layout: "traditional",
    title: "Top L2",
    prompt: "ग च त थ ग त च थ त ग थ च",
    order: 105,
    category: "top",
    difficulty: 2,
  },
  {
    id: "cl-top-3",
    layout: "traditional",
    title: "Top L3",
    prompt: "ग च त थ ध भ य उ थ ग ध च भ य त ग उ थ ध ग भ च",
    order: 106,
    category: "top",
    difficulty: 3,
  },
  {
    id: "cl-bottom-1",
    layout: "traditional",
    title: "Bottom L1",
    prompt: "शशश हहह शशश हहह शशश हहह शशश",
    order: 107,
    category: "bottom",
    difficulty: 1,
  },
  {
    id: "cl-bottom-2",
    layout: "traditional",
    title: "Bottom L2",
    prompt: "श ह अ ख श अ ह ख अ श ख ह",
    order: 108,
    category: "bottom",
    difficulty: 2,
  },
  {
    id: "cl-bottom-3",
    layout: "traditional",
    title: "Bottom L3",
    prompt: "श ह अ ख द ल अ श ख ह ल द ह श अ द ख ल श द ह ख",
    order: 109,
    category: "bottom",
    difficulty: 3,
  },
  {
    id: "cl-all-1",
    layout: "traditional",
    title: "All L1",
    prompt: "ममम पपप ककक खखख ममम पपप ककक",
    order: 110,
    category: "all",
    difficulty: 1,
  },
  {
    id: "cl-all-2",
    layout: "traditional",
    title: "All L2",
    prompt: "म प क ख न त ब ल म क प ख त न ल ब",
    order: 111,
    category: "all",
    difficulty: 2,
  },
  {
    id: "cl-all-3",
    layout: "traditional",
    title: "All L3",
    prompt: "म प क ख न त ब ल च छ व श म क प ख न ल त ब च प व छ श",
    order: 112,
    category: "all",
    difficulty: 3,
  },
  {
    id: "cl-home-1-en",
    layout: "qwerty",
    title: "Home L1",
    prompt: "aaa sss aaa sss aaa sss aaa",
    order: 201,
    category: "home",
    difficulty: 1,
  },
  {
    id: "cl-home-2-en",
    layout: "qwerty",
    title: "Home L2",
    prompt: "a s d f a d s f d a f s",
    order: 202,
    category: "home",
    difficulty: 2,
  },
  {
    id: "cl-home-3-en",
    layout: "qwerty",
    title: "Home L3",
    prompt: "a s d f g h j a f d s g j h d a f s g a j d h",
    order: 203,
    category: "home",
    difficulty: 3,
  },
  {
    id: "cl-top-1-en",
    layout: "qwerty",
    title: "Top L1",
    prompt: "qqq www qqq www qqq www qqq",
    order: 204,
    category: "top",
    difficulty: 1,
  },
  {
    id: "cl-top-2-en",
    layout: "qwerty",
    title: "Top L2",
    prompt: "q w e r q e w r e q r w",
    order: 205,
    category: "top",
    difficulty: 2,
  },
  {
    id: "cl-top-3-en",
    layout: "qwerty",
    title: "Top L3",
    prompt: "q w e r t y q e w r t y e q r w t q y e r",
    order: 206,
    category: "top",
    difficulty: 3,
  },
  {
    id: "cl-bottom-1-en",
    layout: "qwerty",
    title: "Bottom L1",
    prompt: "zzz xxx zzz xxx zzz xxx zzz",
    order: 207,
    category: "bottom",
    difficulty: 1,
  },
  {
    id: "cl-bottom-2-en",
    layout: "qwerty",
    title: "Bottom L2",
    prompt: "z x c v z c x v c z v x",
    order: 208,
    category: "bottom",
    difficulty: 2,
  },
  {
    id: "cl-bottom-3-en",
    layout: "qwerty",
    title: "Bottom L3",
    prompt: "z x c v b n z c x v b n c z v x n b v z x c n",
    order: 209,
    category: "bottom",
    difficulty: 3,
  },
  {
    id: "cl-all-1-en",
    layout: "qwerty",
    title: "All L1",
    prompt: "aaa qqq zzz sss www xxx aaa",
    order: 210,
    category: "all",
    difficulty: 1,
  },
  {
    id: "cl-all-2-en",
    layout: "qwerty",
    title: "All L2",
    prompt: "a q z s w x d c a s q x w d z c",
    order: 211,
    category: "all",
    difficulty: 2,
  },
  {
    id: "cl-all-3-en",
    layout: "qwerty",
    title: "All L3",
    prompt: "a q z s w x d c e v f b a d s q c x w e z v f",
    order: 212,
    category: "all",
    difficulty: 3,
  },
];

/** Lint every bundled drill row against the difficulty rule. */
export function lintClassicDrills(rows: Lesson[] = CLASSIC_DRILLS): string[] {
  const bad: string[] = [];
  for (const r of rows) {
    const diff = r.difficulty ?? 1;
    const units = splitUnits(r.prompt).filter((u) => u !== " ");
    if (!drillPassesDifficulty(units, diff)) bad.push(r.id);
  }
  return bad;
}
